# posse — generated by scripts/tap-formula.sh in ranger360ai/posse. Do not hand-edit:
# the next release overwrites it. Fix the generator instead.
class Posse < Formula
  desc "Dispatcher binding personas, env sets and recipes to herdr and beads"
  homepage "https://github.com/ranger360ai/posse"
  version "0.5.0"
  license "Apache-2.0"

  bottle do
    root_url "https://github.com/ranger360ai/posse/releases/download/v0.5.0"
    sha256 cellar: :any_skip_relocation, arm64_big_sur: "418d72d3f375999d6f43174da226895178f0225ed1307c8df1e14694bfd77c9b"
    sha256 cellar: :any_skip_relocation, big_sur:       "4724535fe7cbba04dc2360a13ab6307f9722df042a117964f844700c96b9154a"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "1f3054f4f6656e358d132bdc44a116b2a66eeffcbb3d81dd36370067cc967169"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "ded46310be4082deec41f1df8f10748efd16ed9cd4fbb5b74744d21d5357823d"
  end

  on_macos do
    on_arm do
      url "https://github.com/ranger360ai/posse/releases/download/v0.5.0/posse_0.5.0_darwin_arm64.tar.gz"
      sha256 "74a1a83d614724b9ed1a44f98eebf0557d6ecf1894e69d426ef9c616d19fc095"
    end
    on_intel do
      url "https://github.com/ranger360ai/posse/releases/download/v0.5.0/posse_0.5.0_darwin_amd64.tar.gz"
      sha256 "6469fb665bcdd9785751c5f5a07a514f3fb2c0bc0a5879902eec7e06fa095dfb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ranger360ai/posse/releases/download/v0.5.0/posse_0.5.0_linux_arm64.tar.gz"
      sha256 "eec1acdd443390902a0b695385594ac4bd6f1b3e2f2cb4de273392222dce6898"
    end
    on_intel do
      url "https://github.com/ranger360ai/posse/releases/download/v0.5.0/posse_0.5.0_linux_amd64.tar.gz"
      sha256 "797fe8da5fd79bf73fc7cc71a2267b76a55378702f38e9550f5a552000cb5ef1"
    end
  end

  def install
    bin.install "posse"
    doc.install "README.md", "INSTALL.md"
  end

  # No `depends_on` for either substrate, on purpose.
  #
  #   herdr  is not in Homebrew at all, and its own installer refuses to run
  #          under a package manager.
  #   beads  IS in Homebrew — at 1.2.x, which is the WRONG one. 1.2 replaced
  #          the SQLite backend with embedded Dolt, does not read
  #          .beads/beads.db, and auto-inits a stale fork of your queue on the
  #          first call. A `depends_on "beads"` here would hand every new
  #          installer a silently forked work graph. posse pins 0.49.1.
  def caveats
    <<~EOS
      posse needs two substrates Homebrew does not install for it:

        herdr >= 0.8      https://herdr.dev
        bd (beads) 0.49.1 EXACTLY — the upstream release binary, NOT
                          `brew install beads` (that is 1.2.x, which cannot
                          read .beads/beads.db and forks your queue silently).

      Then stand up an instance:

        posse init
        posse version

      The cold-start runbook is #{doc}/INSTALL.md.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/posse version")
  end
end
