# posse — generated by scripts/tap-formula.sh in ranger360ai/posse. Do not hand-edit:
# the next release overwrites it. Fix the generator instead.
class Posse < Formula
  desc "Dispatcher binding personas, env sets and recipes to herdr and beads"
  homepage "https://github.com/ranger360ai/posse"
  version "0.5.1"
  license "Apache-2.0"

  bottle do
    root_url "https://github.com/ranger360ai/posse/releases/download/v0.5.1"
    sha256 cellar: :any_skip_relocation, arm64_big_sur: "3615cc19739c38f47afe141fbe6c2b3faca210e0a2f70ff5ba3a97f133e3e1b2"
    sha256 cellar: :any_skip_relocation, big_sur:       "df9d0ba82a67b2d75a5041966138c352236b070557ad4e54d075920156c23bae"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "7bc85b20fba0695165dac57986bf5394fdda414a0ba36d724ce10fe1fb367390"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "9f79f22d172e97e9b937db533c6d71222640a1935c32744030ec460c7c84cacf"
  end

  on_macos do
    on_arm do
      url "https://github.com/ranger360ai/posse/releases/download/v0.5.1/posse_0.5.1_darwin_arm64.tar.gz"
      sha256 "0adcdfc6acff7091dc08ad1d862414dfe4036e6b7352ecab690620086b37f91e"
    end
    on_intel do
      url "https://github.com/ranger360ai/posse/releases/download/v0.5.1/posse_0.5.1_darwin_amd64.tar.gz"
      sha256 "37ef1f037f94e1fe2acc056c3d2d984f874cb1f80afdc44cd53f29b002b79abe"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ranger360ai/posse/releases/download/v0.5.1/posse_0.5.1_linux_arm64.tar.gz"
      sha256 "b1e5d97b463ac5d429bb88313be5fd56d5b65cfc6a1278ac94c4953d06d43f50"
    end
    on_intel do
      url "https://github.com/ranger360ai/posse/releases/download/v0.5.1/posse_0.5.1_linux_amd64.tar.gz"
      sha256 "0754955b0b0954db1e440ffa9ebca8d64ec9cdf2968faa7d0b4cc2bda9bb53d3"
    end
  end

  def install
    bin.install "posse"
    doc.install "README.md", "INSTALL.md"
  end

  # No `depends_on` for either substrate, on purpose.
  #
  #   herdr  is not in Homebrew at all, and its own installer refuses to run
  #          under a package manager.
  #   beads  IS in Homebrew — at 1.2.x, which is the WRONG one. 1.2 replaced
  #          the SQLite backend with embedded Dolt, does not read
  #          .beads/beads.db, and auto-inits a stale fork of your queue on the
  #          first call. A `depends_on "beads"` here would hand every new
  #          installer a silently forked work graph. posse pins 0.49.1.
  def caveats
    <<~EOS
      posse needs two substrates Homebrew does not install for it:

        herdr >= 0.8      https://herdr.dev
        bd (beads) 0.49.1 EXACTLY — the upstream release binary, NOT
                          `brew install beads` (that is 1.2.x, which cannot
                          read .beads/beads.db and forks your queue silently).

      Then stand up an instance:

        posse init
        posse version

      The cold-start runbook is #{doc}/INSTALL.md.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/posse version")
  end
end
